name: C/C++ CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: setup
              run: cd tests/data && bash setup.bash
            - name: build
              run: mkdir build && cd build && cmake .. && make -j `nproc`
            - name: build_asan
              run: mkdir build_asan && cd build_asan && cmake -DENABLE_ASAN=ON .. && make -j `nproc`
            - name: build_tsan
              run: mkdir build_tsan && cd build_tsan && cmake -DENABLE_TSAN=ON .. && make -j `nproc`
            - name: build_ubsan
              run: mkdir build_ubsan && cd build_ubsan && cmake -DENABLE_UBSAN=ON .. && make -j `nproc`
            - name: Upload builds
              uses: actions/upload-artifact@v4
              with:
                  name: builds
                  path: build*
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                  name: builds
                  path: builds
            - name: setup data
              run: |
                  cd tests/data && bash setup.bash
                  export ILIAD_FILE=${PWD}/tests/data/iliad.data
            - name: test
              run: |
                  cd builds/build
                  chmod +x tests/tests
                  tests/tests
            - name: test_ubsan
              run: |
                  cd builds/build_ubsan
                  chmod +x tests/tests
                  tests/tests
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Install clang-format
              run: sudo apt install -y clang-format
            - uses: actions/checkout@v4
            - name: Check clang-format
              run: find ./ -iname '*.h' -o -iname '*.cpp' | xargs clang-format -n --Werror
