name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: mkdir build && cd build && cmake .. && make -j `nproc`
    - name: build_asan
      run: mkdir build_asan && cd build_asan && cmake -DENABLE_ASAN=ON .. && make -j `nproc`
    - name: build_tsan
      run: mkdir build_msan && cd build_msan && cmake -DENABLE_TSAN=ON .. && make -j `nproc`
    - name: build_ubsan
      run: mkdir build_ubsan && cd build_ubsan && cmake -DENABLE_UBSAN=ON .. && make -j `nproc`
    - name: test
      run: cd build && ./tests/tests
